image:
  repository: ghcr.io/artempt239/ns-scheduler
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: latest
  pullSecrets: []

dashboard:
  enabled: true
  resources: {}

  ingress:
    host:
    gateway:

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

scheduler:
  resources: {}

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  serviceAccount:
    # Annotations to add to the service account
    annotations: {}

  ingress:
    host:
    gateway:

  config:
    schedules: {}
#      empty:
#        timezone: UTC
#        weekdays: []
#        holidays: []
#      main:
#        # Timezone used for time specs in the schedule
#        timezone: UTC
#        # Moments for starting and stopping environments could be described with "weekdays" - a weekly schedule
#        # and "holidays" - full datetime pairs for starts and stops. "Weekdays" schedules do not apply inside time
#        # intervals described by "holidays"
#        weekdays:
#          # Monday = 1, Sunday = 7
#          - days: [ 1,2,3,4 ]
#            start: 08:00
#            stop: 01:00
#          - days: [ 5 ]
#            stop: 01:00
#          - days: [ 6 ]
#            # Both start and stop fields can be either times or lists of times
#            start:
#              - 03:00
#              - 08:00
#            stop:
#              - 01:00
#              - 04:00
#        holidays:
#          # Make sure to use "YYYY-mm-dd HH:MM" or "YYYY-mm-dd HH:MM:SS" formats for start and stop times
#          # The stop times must precede the start times
#          - stop: 2022-12-22 23:00
#            start: 2023-01-03 08:00
#          - stop: 2023-01-06 23:00
#            start: 2023-01-08 08:00
#        # If weekday and holiday moments have the same timestamp - holiday action will be performed
#        # (and weekend action will be ignored)

    # Environment is a named collection of namespaces to be manipulated as a whole
    envs: {}
#      project-1:
#        namespaces:
#          - project-1
#        schedule: empty
#      project-2:
#        namespaces:
#          - project-2-data
#          - project-2-services
#        schedule: main
