apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  scheduler-config.yaml: |
    {{- toYaml .Values.scheduler.config | nindent 4 }}
